
namespace MCPArrayTests;


[TestFixture]
[FeatureDescription(
@"As a developer using the MCP PDF server
I want to test the PDF generation functionality
So that I can ensure the system works correctly")]
public partial class ArrayFeatureTests : FeatureFixture, IAsyncDisposable
{
    [Test]
    [Scenario]
    [TestCase(
"""
[
{"Name":"Ignat","Surname":"Andrei","Email":"ignatandrei@yahoo.com"},
{"Name":"Adam","Surname":"Kowalski","Email":"adam.kowalski@notExisting.com"},
]
""",
"""
<table border="1">
    <thead>
        <tr>
            <th>Nr</th>                    <th>Name</th>
            <th>Surname</th>
            <th>Email</th>
    </thead>
    <tbody>
            <tr>
                <td>1</td>
                    <td>Ignat</td>
                    <td>Andrei</td>
                    <td>ignatandrei@yahoo.com</td>
            </tr>
            <tr>
                <td>2</td>
                    <td>Adam</td>
                    <td>Kowalski</td>
                    <td>adam.kowalski@notExisting.com</td>
            </tr>

</table>
Generated by https://github.com/ignatandrei/MCP_PDF
"""
        )]
    public async Task VerifyArrayToHTML(string jsonArray, string htmlResult)
    {
        await Runner.RunScenarioAsync(
            _ => Given_I_have_an_json_array_as_string(jsonArray),
            _ => When_I_Convert_ToHtml(),
            _ => Then_the_result_should_be(htmlResult)
        );
    }

    [Test]
    [Scenario]
    [TestCase(
"""
[
{"Name":"Ignat","Surname":"Andrei","Email":"ignatandrei@yahoo.com"},
{"Name":"Adam","Surname":"Kowalski","Email":"adam.kowalski@notExisting.com"},
]
""")]
    public async Task VerifyArrayToPDF(string jsonArray)
    {
        await Runner.RunScenarioAsync(
            _ => Given_I_have_an_json_array_as_string(jsonArray),
            _ => When_I_Convert_ToPDF(),
            _ => Then_the_pdf_result_should_be_valid()
        );
    }

    [Test]
    [Scenario]
    [TestCase(
"""
[
{"Name":"Ignat","Surname":"Andrei","Email":"ignatandrei@yahoo.com"},
{"Name":"Adam","Surname":"Kowalski","Email":"adam.kowalski@notExisting.com"},
]
""",
"""
NR,Name,Surname,Email
1,Ignat,Andrei,ignatandrei@yahoo.com
2,Adam,Kowalski,adam.kowalski@notExisting.com
"""
        )]
    public async Task VerifyArrayToCSV(string jsonArray, string csvResult)
    {
        await Runner.RunScenarioAsync(
            _ => Given_I_have_an_json_array_as_string(jsonArray),
            _ => When_I_Convert_ToCSV(),
            _ => Then_the_csv_result_should_be(csvResult)
        );
    }

    string arrToTest = string.Empty;
    string htmlResult = string.Empty;
    string csvResult = string.Empty;
    byte[] pdfResult = [];
    ArrayToAny? arrayToAny;
    private ILogger<ArrayToAny> _logger;

    [OneTimeSetUp]
    public void Setup()
    {
        // Create a mock logger for testing
        var loggerFactory = LoggerFactory.Create(builder => builder.AddConsole());
        _logger = loggerFactory.CreateLogger<ArrayToAny>();
        //_logger  = new NullLogger<ArrayToAny>();
        arrayToAny = new ArrayToAny(_logger);
    }

    [OneTimeTearDown]
    public async Task TearDown()
    {
        if (arrayToAny != null)
        {
            await arrayToAny.DisposeAsync();
        }
    }

    private Task Given_I_have_an_json_array_as_string(string arr)
    {
        arrToTest = arr;
        return Task.CompletedTask;
    }
    private async Task When_I_Convert_ToHtml()
    {
        var loggerFactory = LoggerFactory.Create(builder => builder.AddConsole());
        var logger = loggerFactory.CreateLogger<ArrayToAny>();
        //_logger  = new NullLogger<ArrayToAny>();
        htmlResult = await (new ArrayToAny(logger)).ConvertArrayToHTML(arrToTest);
        return;
    }

    private async Task When_I_Convert_ToPDF()
    {
        pdfResult = await arrayToAny!.ConvertArrayToPDF(arrToTest);
        //await File.WriteAllBytesAsync(@"D:\test.pdf", pdfResult);
        return;
    }

    private async Task When_I_Convert_ToCSV()
    {
        csvResult = await arrayToAny!.ConvertArrayToCSV(arrToTest);
        //await File.WriteAllTextAsync(@"D:\a.csv", csvResult);
        return;
    }

    private async Task Then_the_result_should_be(string html)
    {
        //await File.WriteAllTextAsync(@"D:\htmlResult.html", htmlResult);
        //await File.WriteAllTextAsync(@"D:\htmlExpected.html", html);
        html = html.Replace(" ", "").Replace("\r", "").Replace("\n", "");
        htmlResult = htmlResult.Replace(" ", "").Replace("\r", "").Replace("\n", "");
        var min = Math.Min(html.Length, htmlResult.Length);
        htmlResult.Length.ShouldBe(min, $"Length mismatch: expected {html.Length}, got {htmlResult.Length}");
        html.Length.ShouldBe(min);
        for (int i = 0; i < min; i++)
        {
            htmlResult[i].ShouldBe(html[i], $"Mismatch at index {i}: expected '{html[i]}', got '{htmlResult[i]}'");
        }
        htmlResult.ShouldBe(html);
        return;
    }

    private Task Then_the_pdf_result_should_be_valid()
    {
        // Verify PDF is not null or empty
        pdfResult.ShouldNotBeNull();
        pdfResult.Length.ShouldBeGreaterThan(0);

        // Verify PDF header (PDFs start with %PDF-)
        var pdfHeader = System.Text.Encoding.ASCII.GetString(pdfResult.Take(5).ToArray());
        pdfHeader.ShouldBe("%PDF-");

        // Verify PDF contains some expected content markers

        return Task.CompletedTask;
    }

    private Task Then_the_csv_result_should_be(string csv)
    {
        csv = csv.Replace("\r", "").Replace("\n", "");
        csvResult = csvResult.Replace("\r", "").Replace("\n", "");
        csvResult.ShouldBe(csv);
        return Task.CompletedTask;
    }

    public async ValueTask DisposeAsync()
    {
        if (arrayToAny != null)
        {
            await arrayToAny.DisposeAsync();
        }
        GC.SuppressFinalize(this);
    }
}