global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using DocumentFormat.OpenXml.Spreadsheet;
global using DocumentFormat.OpenXml.Wordprocessing;
global using MCPArrayExport.Data;
global using PuppeteerSharp;
global using System.ComponentModel;
global using System.Text.Json;
global using WordProcess = DocumentFormat.OpenXml.Wordprocessing;
global using DocumentFormat.OpenXml.Packaging;
